// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kvs.proto

#include "kvs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_common_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_common_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BucketKeyAddress;
}  // namespace protobuf_common_2eproto
class KeyQueryRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KeyQueryRequest>
      _instance;
} _KeyQueryRequest_default_instance_;
class KeyQueryResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KeyQueryResponse>
      _instance;
} _KeyQueryResponse_default_instance_;
class KeyNotifyRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KeyNotifyRequest>
      _instance;
} _KeyNotifyRequest_default_instance_;
class KeyNotifyResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KeyNotifyResponse>
      _instance;
} _KeyNotifyResponse_default_instance_;
namespace protobuf_kvs_2eproto {
static void InitDefaultsKeyQueryRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_KeyQueryRequest_default_instance_;
    new (ptr) ::KeyQueryRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KeyQueryRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KeyQueryRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKeyQueryRequest}, {
      &protobuf_common_2eproto::scc_info_BucketKeyAddress.base,}};

static void InitDefaultsKeyQueryResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_KeyQueryResponse_default_instance_;
    new (ptr) ::KeyQueryResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KeyQueryResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KeyQueryResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKeyQueryResponse}, {
      &protobuf_common_2eproto::scc_info_BucketKeyAddress.base,}};

static void InitDefaultsKeyNotifyRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_KeyNotifyRequest_default_instance_;
    new (ptr) ::KeyNotifyRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KeyNotifyRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KeyNotifyRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKeyNotifyRequest}, {
      &protobuf_common_2eproto::scc_info_BucketKeyAddress.base,}};

static void InitDefaultsKeyNotifyResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_KeyNotifyResponse_default_instance_;
    new (ptr) ::KeyNotifyResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KeyNotifyResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_KeyNotifyResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsKeyNotifyResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_KeyQueryRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KeyQueryResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KeyNotifyRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KeyNotifyResponse.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryRequest, response_address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryRequest, addresses_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryRequest, request_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryResponse, addresses_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryResponse, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyQueryResponse, response_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyRequest, response_address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyRequest, addresses_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyRequest, active_trigger_names_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyRequest, request_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyResponse, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyResponse, key_counts_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KeyNotifyResponse, response_id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::KeyQueryRequest)},
  { 8, -1, sizeof(::KeyQueryResponse)},
  { 16, -1, sizeof(::KeyNotifyRequest)},
  { 25, -1, sizeof(::KeyNotifyResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_KeyQueryRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_KeyQueryResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_KeyNotifyRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_KeyNotifyResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "kvs.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tkvs.proto\032\014common.proto\"e\n\017KeyQueryReq"
      "uest\022\030\n\020response_address\030\001 \001(\t\022$\n\taddres"
      "ses\030\002 \003(\0132\021.BucketKeyAddress\022\022\n\nrequest_"
      "id\030\003 \001(\t\"g\n\020KeyQueryResponse\022$\n\taddresse"
      "s\030\001 \003(\0132\021.BucketKeyAddress\022\030\n\005error\030\002 \001("
      "\0162\t.KVSError\022\023\n\013response_id\030\003 \001(\t\"\204\001\n\020Ke"
      "yNotifyRequest\022\030\n\020response_address\030\001 \001(\t"
      "\022$\n\taddresses\030\002 \003(\0132\021.BucketKeyAddress\022\034"
      "\n\024active_trigger_names\030\003 \003(\t\022\022\n\nrequest_"
      "id\030\004 \001(\t\"V\n\021KeyNotifyResponse\022\030\n\005error\030\001"
      " \001(\0162\t.KVSError\022\022\n\nkey_counts\030\002 \003(\r\022\023\n\013r"
      "esponse_id\030\003 \001(\t*\033\n\016KeyRequestType\022\t\n\005FE"
      "TCH\020\000*3\n\022HelperResponseType\022\016\n\nREMOTE_GE"
      "T\020\000\022\r\n\tNOTIF_PUT\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 546);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kvs.proto", &protobuf_RegisterTypes);
  ::protobuf_common_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_kvs_2eproto
const ::google::protobuf::EnumDescriptor* KeyRequestType_descriptor() {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_kvs_2eproto::file_level_enum_descriptors[0];
}
bool KeyRequestType_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* HelperResponseType_descriptor() {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_kvs_2eproto::file_level_enum_descriptors[1];
}
bool HelperResponseType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void KeyQueryRequest::InitAsDefaultInstance() {
}
void KeyQueryRequest::clear_addresses() {
  addresses_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyQueryRequest::kResponseAddressFieldNumber;
const int KeyQueryRequest::kAddressesFieldNumber;
const int KeyQueryRequest::kRequestIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyQueryRequest::KeyQueryRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kvs_2eproto::scc_info_KeyQueryRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyQueryRequest)
}
KeyQueryRequest::KeyQueryRequest(const KeyQueryRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      addresses_(from.addresses_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  response_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.response_address().size() > 0) {
    response_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_address_);
  }
  request_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.request_id().size() > 0) {
    request_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_id_);
  }
  // @@protoc_insertion_point(copy_constructor:KeyQueryRequest)
}

void KeyQueryRequest::SharedCtor() {
  response_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

KeyQueryRequest::~KeyQueryRequest() {
  // @@protoc_insertion_point(destructor:KeyQueryRequest)
  SharedDtor();
}

void KeyQueryRequest::SharedDtor() {
  response_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KeyQueryRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KeyQueryRequest::descriptor() {
  ::protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KeyQueryRequest& KeyQueryRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kvs_2eproto::scc_info_KeyQueryRequest.base);
  return *internal_default_instance();
}


void KeyQueryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyQueryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  addresses_.Clear();
  response_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool KeyQueryRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyQueryRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string response_address = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_address().data(), static_cast<int>(this->response_address().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyQueryRequest.response_address"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .BucketKeyAddress addresses = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_addresses()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string request_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_request_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->request_id().data(), static_cast<int>(this->request_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyQueryRequest.request_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyQueryRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyQueryRequest)
  return false;
#undef DO_
}

void KeyQueryRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyQueryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_address().data(), static_cast<int>(this->response_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryRequest.response_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->response_address(), output);
  }

  // repeated .BucketKeyAddress addresses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->addresses(static_cast<int>(i)),
      output);
  }

  // string request_id = 3;
  if (this->request_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request_id().data(), static_cast<int>(this->request_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryRequest.request_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->request_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KeyQueryRequest)
}

::google::protobuf::uint8* KeyQueryRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KeyQueryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_address().data(), static_cast<int>(this->response_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryRequest.response_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->response_address(), target);
  }

  // repeated .BucketKeyAddress addresses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->addresses(static_cast<int>(i)), deterministic, target);
  }

  // string request_id = 3;
  if (this->request_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request_id().data(), static_cast<int>(this->request_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryRequest.request_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->request_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KeyQueryRequest)
  return target;
}

size_t KeyQueryRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KeyQueryRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .BucketKeyAddress addresses = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->addresses_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->addresses(static_cast<int>(i)));
    }
  }

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_address());
  }

  // string request_id = 3;
  if (this->request_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->request_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KeyQueryRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyQueryRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyQueryRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyQueryRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyQueryRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyQueryRequest)
    MergeFrom(*source);
  }
}

void KeyQueryRequest::MergeFrom(const KeyQueryRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyQueryRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  addresses_.MergeFrom(from.addresses_);
  if (from.response_address().size() > 0) {

    response_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_address_);
  }
  if (from.request_id().size() > 0) {

    request_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_id_);
  }
}

void KeyQueryRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyQueryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyQueryRequest::CopyFrom(const KeyQueryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyQueryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyQueryRequest::IsInitialized() const {
  return true;
}

void KeyQueryRequest::Swap(KeyQueryRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyQueryRequest::InternalSwap(KeyQueryRequest* other) {
  using std::swap;
  CastToBase(&addresses_)->InternalSwap(CastToBase(&other->addresses_));
  response_address_.Swap(&other->response_address_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  request_id_.Swap(&other->request_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KeyQueryRequest::GetMetadata() const {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void KeyQueryResponse::InitAsDefaultInstance() {
}
void KeyQueryResponse::clear_addresses() {
  addresses_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyQueryResponse::kAddressesFieldNumber;
const int KeyQueryResponse::kErrorFieldNumber;
const int KeyQueryResponse::kResponseIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyQueryResponse::KeyQueryResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kvs_2eproto::scc_info_KeyQueryResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyQueryResponse)
}
KeyQueryResponse::KeyQueryResponse(const KeyQueryResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      addresses_(from.addresses_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  response_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.response_id().size() > 0) {
    response_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_id_);
  }
  error_ = from.error_;
  // @@protoc_insertion_point(copy_constructor:KeyQueryResponse)
}

void KeyQueryResponse::SharedCtor() {
  response_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_ = 0;
}

KeyQueryResponse::~KeyQueryResponse() {
  // @@protoc_insertion_point(destructor:KeyQueryResponse)
  SharedDtor();
}

void KeyQueryResponse::SharedDtor() {
  response_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KeyQueryResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KeyQueryResponse::descriptor() {
  ::protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KeyQueryResponse& KeyQueryResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kvs_2eproto::scc_info_KeyQueryResponse.base);
  return *internal_default_instance();
}


void KeyQueryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyQueryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  addresses_.Clear();
  response_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_ = 0;
  _internal_metadata_.Clear();
}

bool KeyQueryResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyQueryResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .BucketKeyAddress addresses = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_addresses()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .KVSError error = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_error(static_cast< ::KVSError >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string response_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_id().data(), static_cast<int>(this->response_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyQueryResponse.response_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyQueryResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyQueryResponse)
  return false;
#undef DO_
}

void KeyQueryResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyQueryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BucketKeyAddress addresses = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->addresses(static_cast<int>(i)),
      output);
  }

  // .KVSError error = 2;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->error(), output);
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_id().data(), static_cast<int>(this->response_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryResponse.response_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->response_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KeyQueryResponse)
}

::google::protobuf::uint8* KeyQueryResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KeyQueryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BucketKeyAddress addresses = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->addresses(static_cast<int>(i)), deterministic, target);
  }

  // .KVSError error = 2;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->error(), target);
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_id().data(), static_cast<int>(this->response_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyQueryResponse.response_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->response_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KeyQueryResponse)
  return target;
}

size_t KeyQueryResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KeyQueryResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .BucketKeyAddress addresses = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->addresses_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->addresses(static_cast<int>(i)));
    }
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_id());
  }

  // .KVSError error = 2;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KeyQueryResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyQueryResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyQueryResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyQueryResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyQueryResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyQueryResponse)
    MergeFrom(*source);
  }
}

void KeyQueryResponse::MergeFrom(const KeyQueryResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyQueryResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  addresses_.MergeFrom(from.addresses_);
  if (from.response_id().size() > 0) {

    response_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_id_);
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void KeyQueryResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyQueryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyQueryResponse::CopyFrom(const KeyQueryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyQueryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyQueryResponse::IsInitialized() const {
  return true;
}

void KeyQueryResponse::Swap(KeyQueryResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyQueryResponse::InternalSwap(KeyQueryResponse* other) {
  using std::swap;
  CastToBase(&addresses_)->InternalSwap(CastToBase(&other->addresses_));
  response_id_.Swap(&other->response_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KeyQueryResponse::GetMetadata() const {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void KeyNotifyRequest::InitAsDefaultInstance() {
}
void KeyNotifyRequest::clear_addresses() {
  addresses_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyNotifyRequest::kResponseAddressFieldNumber;
const int KeyNotifyRequest::kAddressesFieldNumber;
const int KeyNotifyRequest::kActiveTriggerNamesFieldNumber;
const int KeyNotifyRequest::kRequestIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyNotifyRequest::KeyNotifyRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kvs_2eproto::scc_info_KeyNotifyRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyNotifyRequest)
}
KeyNotifyRequest::KeyNotifyRequest(const KeyNotifyRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      addresses_(from.addresses_),
      active_trigger_names_(from.active_trigger_names_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  response_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.response_address().size() > 0) {
    response_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_address_);
  }
  request_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.request_id().size() > 0) {
    request_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_id_);
  }
  // @@protoc_insertion_point(copy_constructor:KeyNotifyRequest)
}

void KeyNotifyRequest::SharedCtor() {
  response_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

KeyNotifyRequest::~KeyNotifyRequest() {
  // @@protoc_insertion_point(destructor:KeyNotifyRequest)
  SharedDtor();
}

void KeyNotifyRequest::SharedDtor() {
  response_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KeyNotifyRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KeyNotifyRequest::descriptor() {
  ::protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KeyNotifyRequest& KeyNotifyRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kvs_2eproto::scc_info_KeyNotifyRequest.base);
  return *internal_default_instance();
}


void KeyNotifyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyNotifyRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  addresses_.Clear();
  active_trigger_names_.Clear();
  response_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool KeyNotifyRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyNotifyRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string response_address = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_address().data(), static_cast<int>(this->response_address().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyNotifyRequest.response_address"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .BucketKeyAddress addresses = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_addresses()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string active_trigger_names = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_active_trigger_names()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->active_trigger_names(this->active_trigger_names_size() - 1).data(),
            static_cast<int>(this->active_trigger_names(this->active_trigger_names_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyNotifyRequest.active_trigger_names"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string request_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_request_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->request_id().data(), static_cast<int>(this->request_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyNotifyRequest.request_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyNotifyRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyNotifyRequest)
  return false;
#undef DO_
}

void KeyNotifyRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyNotifyRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_address().data(), static_cast<int>(this->response_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.response_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->response_address(), output);
  }

  // repeated .BucketKeyAddress addresses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->addresses(static_cast<int>(i)),
      output);
  }

  // repeated string active_trigger_names = 3;
  for (int i = 0, n = this->active_trigger_names_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->active_trigger_names(i).data(), static_cast<int>(this->active_trigger_names(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.active_trigger_names");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->active_trigger_names(i), output);
  }

  // string request_id = 4;
  if (this->request_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request_id().data(), static_cast<int>(this->request_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.request_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->request_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KeyNotifyRequest)
}

::google::protobuf::uint8* KeyNotifyRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KeyNotifyRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_address().data(), static_cast<int>(this->response_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.response_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->response_address(), target);
  }

  // repeated .BucketKeyAddress addresses = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->addresses_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->addresses(static_cast<int>(i)), deterministic, target);
  }

  // repeated string active_trigger_names = 3;
  for (int i = 0, n = this->active_trigger_names_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->active_trigger_names(i).data(), static_cast<int>(this->active_trigger_names(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.active_trigger_names");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->active_trigger_names(i), target);
  }

  // string request_id = 4;
  if (this->request_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request_id().data(), static_cast<int>(this->request_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyRequest.request_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->request_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KeyNotifyRequest)
  return target;
}

size_t KeyNotifyRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KeyNotifyRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .BucketKeyAddress addresses = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->addresses_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->addresses(static_cast<int>(i)));
    }
  }

  // repeated string active_trigger_names = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->active_trigger_names_size());
  for (int i = 0, n = this->active_trigger_names_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->active_trigger_names(i));
  }

  // string response_address = 1;
  if (this->response_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_address());
  }

  // string request_id = 4;
  if (this->request_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->request_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KeyNotifyRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyNotifyRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyNotifyRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyNotifyRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyNotifyRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyNotifyRequest)
    MergeFrom(*source);
  }
}

void KeyNotifyRequest::MergeFrom(const KeyNotifyRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyNotifyRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  addresses_.MergeFrom(from.addresses_);
  active_trigger_names_.MergeFrom(from.active_trigger_names_);
  if (from.response_address().size() > 0) {

    response_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_address_);
  }
  if (from.request_id().size() > 0) {

    request_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_id_);
  }
}

void KeyNotifyRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyNotifyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyNotifyRequest::CopyFrom(const KeyNotifyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyNotifyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyNotifyRequest::IsInitialized() const {
  return true;
}

void KeyNotifyRequest::Swap(KeyNotifyRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyNotifyRequest::InternalSwap(KeyNotifyRequest* other) {
  using std::swap;
  CastToBase(&addresses_)->InternalSwap(CastToBase(&other->addresses_));
  active_trigger_names_.InternalSwap(CastToBase(&other->active_trigger_names_));
  response_address_.Swap(&other->response_address_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  request_id_.Swap(&other->request_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KeyNotifyRequest::GetMetadata() const {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void KeyNotifyResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyNotifyResponse::kErrorFieldNumber;
const int KeyNotifyResponse::kKeyCountsFieldNumber;
const int KeyNotifyResponse::kResponseIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyNotifyResponse::KeyNotifyResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kvs_2eproto::scc_info_KeyNotifyResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyNotifyResponse)
}
KeyNotifyResponse::KeyNotifyResponse(const KeyNotifyResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      key_counts_(from.key_counts_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  response_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.response_id().size() > 0) {
    response_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_id_);
  }
  error_ = from.error_;
  // @@protoc_insertion_point(copy_constructor:KeyNotifyResponse)
}

void KeyNotifyResponse::SharedCtor() {
  response_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_ = 0;
}

KeyNotifyResponse::~KeyNotifyResponse() {
  // @@protoc_insertion_point(destructor:KeyNotifyResponse)
  SharedDtor();
}

void KeyNotifyResponse::SharedDtor() {
  response_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KeyNotifyResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KeyNotifyResponse::descriptor() {
  ::protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KeyNotifyResponse& KeyNotifyResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kvs_2eproto::scc_info_KeyNotifyResponse.base);
  return *internal_default_instance();
}


void KeyNotifyResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyNotifyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_counts_.Clear();
  response_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_ = 0;
  _internal_metadata_.Clear();
}

bool KeyNotifyResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyNotifyResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .KVSError error = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_error(static_cast< ::KVSError >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 key_counts = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_key_counts())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 18u, input, this->mutable_key_counts())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string response_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_id().data(), static_cast<int>(this->response_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KeyNotifyResponse.response_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyNotifyResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyNotifyResponse)
  return false;
#undef DO_
}

void KeyNotifyResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyNotifyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .KVSError error = 1;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->error(), output);
  }

  // repeated uint32 key_counts = 2;
  if (this->key_counts_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _key_counts_cached_byte_size_));
  }
  for (int i = 0, n = this->key_counts_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->key_counts(i), output);
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_id().data(), static_cast<int>(this->response_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyResponse.response_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->response_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KeyNotifyResponse)
}

::google::protobuf::uint8* KeyNotifyResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KeyNotifyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .KVSError error = 1;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->error(), target);
  }

  // repeated uint32 key_counts = 2;
  if (this->key_counts_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _key_counts_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->key_counts_, target);
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_id().data(), static_cast<int>(this->response_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KeyNotifyResponse.response_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->response_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KeyNotifyResponse)
  return target;
}

size_t KeyNotifyResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KeyNotifyResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated uint32 key_counts = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->key_counts_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _key_counts_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string response_id = 3;
  if (this->response_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_id());
  }

  // .KVSError error = 1;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KeyNotifyResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyNotifyResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyNotifyResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyNotifyResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyNotifyResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyNotifyResponse)
    MergeFrom(*source);
  }
}

void KeyNotifyResponse::MergeFrom(const KeyNotifyResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyNotifyResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  key_counts_.MergeFrom(from.key_counts_);
  if (from.response_id().size() > 0) {

    response_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_id_);
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void KeyNotifyResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyNotifyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyNotifyResponse::CopyFrom(const KeyNotifyResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyNotifyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyNotifyResponse::IsInitialized() const {
  return true;
}

void KeyNotifyResponse::Swap(KeyNotifyResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyNotifyResponse::InternalSwap(KeyNotifyResponse* other) {
  using std::swap;
  key_counts_.InternalSwap(&other->key_counts_);
  response_id_.Swap(&other->response_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KeyNotifyResponse::GetMetadata() const {
  protobuf_kvs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kvs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KeyQueryRequest* Arena::CreateMaybeMessage< ::KeyQueryRequest >(Arena* arena) {
  return Arena::CreateInternal< ::KeyQueryRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KeyQueryResponse* Arena::CreateMaybeMessage< ::KeyQueryResponse >(Arena* arena) {
  return Arena::CreateInternal< ::KeyQueryResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KeyNotifyRequest* Arena::CreateMaybeMessage< ::KeyNotifyRequest >(Arena* arena) {
  return Arena::CreateInternal< ::KeyNotifyRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KeyNotifyResponse* Arena::CreateMaybeMessage< ::KeyNotifyResponse >(Arena* arena) {
  return Arena::CreateInternal< ::KeyNotifyResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
